### ISSUE TITLE
Support nested templates to create nested routes

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/twilio-run#122]
It seems like we are currently not supporting to have nested directories in the templates themselves. This should be supported. It's a blocker for @craigsdennis' PR in the `function-templates` repository.

This command should work but is currently failing because both the `functions` and `assets` directory include an `admin/` directory

```bash
TWILIO_SERVERLESS_TEMPLATE_REPO="craigsdennis/function-templates" twilio serverless:init craig-voice --template="voice-client-javascript"
```

**Comment by craigsdennis** [comment]
@dkundel Do you have any feedback I can work through while we wait for the bug fix?
