### ISSUE TITLE
Missing concept of Private Asset(s)

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/twilio-run#40]
We have the concept of functions and assets but not private assets which means calls like:

```JavaScript
Runtime.getAssets()['config.json'].open();
```

Fails with open is undefined or not a function.  Possibly approaches:

- Check for special comment in asset files and change their load process
- Create/Check a new folder private_assets and load them in a way that provides open()
- add to an existing (of forthcoming) configuration file to mark some assets as private

**Comment by dkundel** [comment]
Hey @ShelbyZ! Thanks for reporting this. I haven't seen the `open()` method documented anywhere myself which is why it doesn't exist.

As for private assets. We'll be releasing version 2 at SIGNAL and it has support for private assets by calling them `.private.` in the filename. There's much more coming with it as well. So I'll close the issue for now.

Thanks for raising this though. I followed up on the `.open()` method with the team to see what's going on there.

**Comment by LukasBicus** [comment]
@dkundel - it would be great to add this info to the documentation. I found information here, when I decided to raise new issue for it.

**Comment by jargetz** [comment]
Has this ever been fixed or updated?  Current documentation seems to indicate to continue doing what the original issue raiser did: https://www.twilio.com/docs/runtime/assets#private-assets. I continue to get the same error.

**Comment by philnash** [comment]
@jargetz The documentation still doesn't mention a `.open()` method, instead [opting to use `fs.readFileSync`](https://www.twilio.com/docs/runtime/assets?code-sample=code-read-the-content-of-a-private-asset-1&code-language=Node.js&code-sdk-version=default). So we don't support a `.open()` method on private assets.

Note that you can make an asset private when using the serverless toolkit by placing `.private` between the file name and the extension. The `.private` part will be stripped out during upload. Check [the documentation on assets and the serverless toolkit here](https://www.twilio.com/docs/labs/serverless-toolkit/general-usage#assets).

Does that help?

**Comment by jargetz** [comment]
Thank you so much for the response!  I see the link you've provided and will make sure to use that going forward.

Here's where I'm getting confused (and I apologize if I'm missing something):

1. Go to: https://www.twilio.com/console/assets
2. Upload an asset and select private
3. See it in the list: It tells you to call `open()`

<img width="1014" alt="Screen Shot 2020-11-08 at 2 19 29 PM" src="https://user-images.githubusercontent.com/1215766/98485774-b4302b00-21cd-11eb-9ea1-3cc145a2d51b.png">

Is this out of sync with the previous documentation you called or am I confusing things?  Thanks again for your help
<img width="254" alt="Screen Shot 2020-11-08 at 2 22 37 PM" src="https://user-images.githubusercontent.com/1215766/98485809-dfb31580-21cd-11eb-93b1-e0e92e82e742.png">

**Comment by philnash** [comment]
Ah, thanks for that information @jargetz. It's funny, since I mainly work with the serverless toolkit, I don't see much of the Functions UI in the console!

I will follow up with the team about the `.open()` method and look to get it implemented within the Serverless Toolkit.

**Comment by philnash** [comment]
@jargetz Apologies, it seems [we do actually support this in the Serverless Toolkit](https://github.com/twilio-labs/serverless-toolkit/blob/main/packages/twilio-run/src/runtime/internal/runtime.ts#L32). It just isn't documented in the toolkit.

So, you are free to use `open()` on private assets.

**Comment by jargetz** [comment]
Thank you for the update!
