### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/twilio-run#53]
Local dev mode should have a `watch` flag that automatically adds newly created files to the files that are being served. It could either just restart the entire server or just update the Routes cache and print a message to the terminal that a new Function or Asset has become available.

**Comment by dsnair** [comment]
Is it okay if I give this a try?

**Comment by philnash** [comment]
Please go ahead @dsnair! I don't believe anyone else is working on this and we would love the contribution. Let us know if you'd like any guidance on the project.

**Comment by imnotjames** [comment]
Given there's already a `live` parameter, should it work alongside that?  EG, a filesystem watcher that clears the route caches when a new file is added / removed when `--live` is specified?

As it stands, `--live` seems to disable any sort of caching of functions (and there doesn't seem to be a good way to disable that).

```
  --live                Always serve from the current functions (no caching)
                                                       [boolean] [default: true]
```

If it should be added to a separate `--watch` that's not too bad to do, just seems to be overlapping features.
