### ISSUE TITLE
husky > prepare-commit-msg hook failed

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/twilio-run#74]
Committing from Windows machine appears to fail on the husky commands (with no real help on what path/file was not found):

![image](https://user-images.githubusercontent.com/1033099/63063464-a0eebc80-beb1-11e9-8d07-45418721a6f6.png)

The prepare-commit-msg command will not work for win32 as is:

```
exec < /dev/tty && git-cz --hook
```

**Comment by dkundel** [comment]
Oh no I'm sorry for that :( Do you happen to have tried it with WSL? 

There's an open issue for this: https://github.com/commitizen/cz-cli/issues/627

I think one solution for now is the following (I'll try to work on that next week):
- Remove the git hook
- Add a script trigger `git-cz` by running `npm run commit`
- Use the Git hooks via Husky to verify the git commit message without providing the UI to create a compliant one.
- Update the contributors guide accordingly

**Comment by dkundel** [comment]
I removed `git-cz` from the hooks and replaced it with an `npm run cm` script.
