### ISSUE TITLE
Private assets require forward slash to access

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/twilio-run#84]
Hosting a private asset appears to use a forward slash in the path which differs from hosting via the Twilio Console.  I would suspect internally it could be added when accessing via Runtime.getAssets()[...] to keep twilio-run inline with console behaviors.  Possibly related to #43 

![image](https://user-images.githubusercontent.com/1033099/66225695-dd5abf80-e68d-11e9-8ccd-937f04bed3af.png)

Trying to access the asset without the forward slash:

![image](https://user-images.githubusercontent.com/1033099/66225907-71c52200-e68e-11e9-91e3-bc1babdf9c2b.png)

Private Asset in Twilio Console: 
![image](https://user-images.githubusercontent.com/1033099/66226473-b9987900-e68f-11e9-9862-c1ec2f7d8f42.png)

Test code:

```JavaScript
exports.handler = function(context, event, callback) {
    let asset_file = 'test.txt';
    let assets = Runtime.getAssets();
    console.log('assets: ', assets);

    const file = Runtime.getAssets()[asset_file].path;
    console.log('file: ', file);

    callback(null, {});
};
```

**Comment by dkundel** [comment]
This seems to be an inconsistency on the hosted side. Because if you deploy via the CLI you'll get the assets with a `/` prefix. I just tried and you can see the example here: https://example-project-4-4151.twil.io/list-assets-2

Using the code: 

```js
exports.handler = function(context, event, callback) {
  const output = Runtime.getAssets();
  callback(null, {
    privateAssets: output,
  });
};
```

I'll forward the inconsistency to the team :)

**Comment by dkundel** [comment]
Hi @ShelbyZ I checked in with the team and it appears like the API automatically preprends the `/` for the assets. So it seems like this is an inconsistency between the API and the Console. We could potentially fix this for `legacyMode` though
